### PR TITLE
Assignment 06

### PR DESCRIPTION
**Pull request by VishwajithP2308**

### CODE REVIEW

**Comment by shivangraikar** [comment]
https://vishwajithp2308.github.io/cs460student/06/index.html

Are you sure this is your link? I do not see any output for virtual robot.

**Comment by VishwajithP2308** [comment]
Yes . That’s the link but I deleted the bg image on my desktop that’s why
you aren’t able to see the bg on it . Please do consider it .

**Comment by shivangraikar** [comment]
But I do not even see your robot on the screen.

**Comment by VishwajithP2308** [comment]
Should I resubmit it . I think there was some problem while uploading.

**Pull request closed without merging**
