### PR TITLE
Assignment06

### PR DESCRIPTION
**Pull request by Likhithasri224**

### CODE REVIEW

**Comment by shivangraikar** [comment]
https://likhithasri224.github.io/cs460student.github.io/02/

Are you sure this is your link? I do not see the output for virtual robot.

**Comment by Likhithasri224** [comment]
Hi Shivang,

Yeah, it’s my link only. I can also send a screenshot of it if you want me to. Please check it once again


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by shivangraikar** [comment]
Please send me the correct link, the webpage gives me error.

**Comment by Likhithasri224** [comment]
Please check this link once.

https://likhithasri224.github.io/cs460student.github.io/

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by shivangraikar** [comment]
The link opens and shows a black web background but I cannot see any robot and effects.

**Comment by Likhithasri224** [comment]
Please let me check once and I will update you.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Likhithasri224** [comment]
Please check this link once.

https://likhithasri224.github.io/cs460student.github.io/02/index6.html

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Likhithasri224** [comment]
Hi Shivang,

I didn’t get grade for my last assignment. Could you please check it once and grade it if possible.

Thankyou

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Pull request closed without merging**
