### PR TITLE
ASSIGNMENT#06

### PR DESCRIPTION
**Pull request by Sruthi7201**

### CODE REVIEW

**Comment by shivangraikar** [comment]
https://sruthi7201.github.io/cs460student/

Are you sure this is your link? I do not see any output for virtual robot!

**Comment by Sruthi7201** [comment]
Hi,
Actually for the previous assignments I will always attach this link (https://github.com/Sruthi7201/cs460student), But my friend suggested me to attach this link (https://sruthi7201.github.io/cs460student/<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsruthi7201.github.io%2Fcs460student%2F&data=05%7C01%7CS.Chirumamilla001%40umb.edu%7C85db693fa5464b32bc9508dabea3c9b2%7Cb97188711ee94425953c1ace1373eb38%7C0%7C0%7C638031907917446440%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=X%2FfyD4DYAPRxj5qaaERrFqikBVS4OQG3yzohSKGZgVk%3D&reserved=0>) for the last assignment, but there is an output for virtual robot, may be the link was wrong. Can you please check it once.


Thanks,
Sruthi      
[https://opengraph.githubassets.com/339bb087642ed5f7f791d3584c8a736821c6d90c7de961a91ddb25b5dac9abf8/Sruthi7201/cs460student]<https://github.com/Sruthi7201/cs460student>
GitHub - Sruthi7201/cs460student: Assignments for CS460.org!<https://github.com/Sruthi7201/cs460student>
Assignments for CS460.org! Contribute to Sruthi7201/cs460student development by creating an account on GitHub.
github.com

________________________________

**Comment by shivangraikar** [comment]
I see, but the problem is with your GitHub page deployment. You should enable and check the deployment. The first link you attached is for your github.com site (the actual files that you uploaded). 

The second link is incorrectly submitted which is wrong with the deployment. Please look into the steps for deployment and send me a new link soon.

**Comment by Sruthi7201** [comment]
I unfortunately unpublished the site. Now I am unable to get the link. Can you please help me with that.
________________________________

**Comment by Sruthi7201** [comment]
(https://sruthi7201.github.io/cs460student/sruthi/index.html) Can you please check this link once.
________________________________

**Pull request closed without merging**
