### PR TITLE
HW4

### PR DESCRIPTION
**Pull request by darksofnic**
https://darksofnic.github.io/cs460student/04/

Incomplete version.

### CODE REVIEW

**Comment by darksofnic** [comment]
https://darksofnic.github.io/cs460student/04/

**Comment by shivangraikar** [comment]
I do not see your pdf, also your airplane is commented, was it intentional?

**Comment by darksofnic** [comment]
Hi , i think I might have forgotten submit the pdf.
But my assignment was incomplete.

**Comment by shivangraikar** [comment]
Well, your first name and last name to put in grades?

**Comment by darksofnic** [comment]
Harvey M Paniagua

**Pull request closed without merging**
