### PR TITLE
Assignment 8 finished

### PR DESCRIPTION
**Pull request by BrianXiaoBin**

### CODE REVIEW

**Comment by shivangraikar** [comment]
Hello, I do not see any github page link or a pdf to check your assignment 8. Please review as soon as possible and update it.

**Comment by BrianXiaoBin** [comment]
Sorry, I forgot to upload it. I just reuploaded. Please check it out.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: shivangraikar ***@***.***>
发送时间: Monday, November 28, 2022 6:04:39 PM
收件人: bostongfx/cs460student ***@***.***>
抄送: XiaoBin Wang ***@***.***>; Author ***@***.***>
主题: Re: [bostongfx/cs460student] Assignment 8 finished (PR #357)

CAUTION: EXTERNAL SENDER

Hello, I do not see any github page link or a pdf to check your assignment 8. Please review as soon as possible and update it.

―

**Comment by shivangraikar** [comment]
I still do not see it.

**Comment by BrianXiaoBin** [comment]
I pulled a new request for it. I can see it on github.
________________________________

**Comment by BrianXiaoBin** [comment]
Can you close for my assignment 8. Cause I can’t send a new PR for assignment 9

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: XiaoBin Wang ***@***.***>
发送时间: Monday, November 28, 2022 8:12:56 PM
收件人: bostongfx/cs460student ***@***.***>
主题: Re: [bostongfx/cs460student] Assignment 8 finished (PR #357)

I pulled a new request for it. I can see it on github.
________________________________

**Pull request closed without merging**
