### PR TITLE
Assignment 3 finished.

### PR DESCRIPTION
**Pull request by talkingEagle**

### CODE REVIEW

**Comment by talkingEagle** [comment]
[CS460_Assignment_03.pdf](https://github.com/bostongfx/cs460student/files/9650908/CS460_Assignment_03.pdf)
Uploaded the pdf via file not git command so it never got sent in the pull request.

**Comment by talkingEagle** [comment]
Hey, 
I screwed up this pull request some how. But If you click on Assignment 3 finished. That is the git commit I did for the HW. 
thanks
Josh

**Comment by shivangraikar** [comment]
I do not see link for github pages

**Comment by talkingEagle** [comment]
https://talkingeagle.github.io/cs460student/03/index.html
sorry I thought i added it in the pdf. I'll know for next time. My bad. 
thanks
josh

**Pull request closed without merging**
